remote_theme: SteveZMTstudios/jekyll-mdui-theme
plugins:
  - jekyll-remote-theme

title: Your Site Title
description: Your site description

show_downloads: true
theme_color: "#0b57d0"
url: "https://youqire.github.io"
baseurl: "scirm-code" # 用户主页仓库留空；项目仓库填 "/<repo>"